name: sea_cense
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  dio: ^5.2.0+1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.2
  path_provider: ^2.1.1
  provider: ^6.0.5
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.1.2
  shimmer_animation: ^2.1.0+1
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
